- platform: workday
  country: 'BE'
  
- platform: iss
  name: "Int Space Station"
  show_on_map: true

- platform: ping
  name: "PS4 Host"
  host: !secret host_ps4
  scan_interval: 300

- platform: ping
  name: "YI Cam"
  host: !secret host_yicam
  scan_interval: 1800

- platform: ping
  name: "GSM Cri"
  host: !secret host_S4
  scan_interval: 300
  
- platform: ping
  name: "GSM Adrien"
  host: !secret host_G4
  scan_interval: 300
  
- platform: ping
  name: "Tab Lise"
  host: !secret host_tab_lise
  scan_interval: 300
  
- platform: ping
  name: "PC Adrien"
  host: !secret host_pc_adrien
  scan_interval: 300

- platform: ping
  name: "PI Jeedom"
  host: !secret host_pi_jeedom
  scan_interval: 1800
  
- platform: ping
  name: "TV LG"
  host: !secret host_tv_lg
  scan_interval: 1800
  
- platform: ping
  name: "Cam Recorder"
  host: !secret host_cam_recorder
  scan_interval: 1800

- platform: mqtt
  state_topic: "NodeMCU/living/POWER"
  name: "Living Présence"
#  value_template: '{{ value_json.POWER }}'

- platform: mqtt
  state_topic: "NodeMCU/lise/POWER"
  name: "Lise Présence"

- platform: mqtt
  state_topic: "NodeMCU/adrien/POWER"
  name: "Adrien Présence"