homeassistant:
  customize: !include custom.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

discovery:
mobile_app:

map:
sun:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant

device_tracker:
  - platform: bbox
    host: 192.168.1.1
    new_device_defaults:
      track_new_devices: true
  - platform: ping
    hosts:
      gsmdave: !secret host_S10
      gsmchri: !secret host_G4
      gsmadri: !secret host_G6
      gsmlise: !secret host_gsm_lise

speedtestdotnet:
  scan_interval:
    hours: 6
  monitored_conditions:
    - ping
    - download
    - upload

media_player:
  - platform: lg_netcast
    host: !secret host_tv_lg
    access_token: !secret tv_token

coinbase:
  api_key: !secret api_coinbase_key
  api_secret: !secret api_coinbase
  account_balance_currencies:
    - BTC
    - ETH
    - ZEC
    - ETC
    - ZRX
  exchange_rate_currencies:
    - BTC
    - ETH
    - ZEC
    - ETC

telegram_bot:
  - platform: polling
    api_key: !secret telegram_key
    allowed_chat_ids:
      - !secret telegram_id

notify:
  - platform: telegram
    name: DVR_Home_Bot
    chat_id: !secret telegram_id

camera: !include camera.yaml
group: !include groups.yaml
automation: !include automations.yaml
binary_sensor: !include binary.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
